[package]
name = "VOXe"
version = "0.1.0"
edition = "2021"
authors = ["Pouya Farahaani <m.p.farahany@gmail.com>"]

[[bin]]
name = "VOXe"
path = "src/main.rs"

[dependencies]
mio-websocket = { git = "https://github.com/nbaksalyar/mio-websocket" }
